### ISSUE TITLE
'Callback was already called' at queue.js:24:28

### ISSUE THREAD

**Issue by renatograel14** [glynnbird/qrate#1]
Hello everyone! 

I got this error in our application. I think it's caused by:
```
queue.js
150      // Avoid trying to start too many processing operations. This can occur
151      // when callbacks resolve synchronously (#1267).
152      if (isProcessing) {
153        return;
154      }
```
Looking at code,  `_next()` function is returning `null`, then `onceOnly` throw the error;
Not sure if they're related but what kind of situation this could happen?

**Comment by glynnbird** [comment]
Tidy up. This is usually "user error", i.e the worker function calls its callback more than once.
